# READ MORE: https://www.spigotmc.org/wiki/plugin-yml/

name: ${project.name}

version: ${project.version}

main: ${project.groupId}.${project.artifactId}.ArtemisPlugin

api-version: 1.14

depend: [CivModCore]

softdepend: []

authors: [Maxopoly]
